shop/urls.py
from django.urls import path
from .views import (ProductsByCategoryListView,
                    ProductDetailClientView)

app_name = 'shop'
urlpatterns = [
    path('products/<slug:slug>/info/', ProductDetailClientView.as_view(), name='product_detail'),
    path('products/<slug:slug>/', ProductsByCategoryListView.as_view(), name='index_category'),
    path('', ProductsByCategoryListView.as_view(), name='index'),
]

shopproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from shopproject import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('staff/', include('shop.urls_staff')),
    path('', include('shop.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from django.urls import reverse
from slugify import slugify


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название')
    slug = models.SlugField(max_length=100, unique=True, editable=False)
    description = models.TextField(verbose_name='Описание', blank=True, null=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        pass
        # return reverse('shop:category_detail', kwargs={'slug': self.slug})

class Product(models.Model):
    name = models.CharField(max_length=200, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание', blank=True, null=True)
    slug = models.SlugField(max_length=200, unique=True, editable=False)
    image = models.ImageField(upload_to='products', blank=True, null=True, verbose_name='Изображение')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Стоимость')
    available = models.BooleanField(default=True, verbose_name='Доступность')
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated = models.DateTimeField(auto_now=True, editable=False)
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE, verbose_name='Категория товара')

    class Meta:
        ordering = ['category', 'name']
        indexes = [
            models.Index(fields=['id']),
            models.Index(fields=['name']),
        ]
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        slug_name = slugify(self.name)
        slug = f'{slug_name}-{self.pk}'
        self.slug = slug
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('staff:product_detail', kwargs={'slug': self.slug})

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    phone = models.CharField(max_length=20)
    birthday = models.DateTimeField()
    image = models.ImageField(upload_to='users')
    city = models.CharField(max_length=30)

shop/forms.py
from django import forms
from .models import Category, Product


class CategoryCreateForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('name', 'description')


class ProductCreateForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = ('slug', 'created_at', 'updated')

shop/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import (CreateView,
                                  DetailView,
                                  ListView,
                                  UpdateView,
                                  DeleteView)

from .forms import CategoryCreateForm, ProductCreateForm
from .models import Category, Product


###########################   АДМИНКА    #########################

# класс для создания новой категории
class CategoryCreateView(CreateView):
    model = Category
    form_class = CategoryCreateForm
    template_name = 'admin_pages/add_category.html'
    success_url = reverse_lazy('staff:categories')


# класс для просмотра категорий
class CategoryListView(ListView):
    model = Category
    template_name = 'admin_pages/list_category.html'
    context_object_name = 'categories'


# Класс для создания товара
class ProductCreateView(CreateView):
    model = Product
    form_class = ProductCreateForm
    template_name = 'admin_pages/add_product.html'
    success_url = reverse_lazy('staff:products')

# Класс для отображения товаров
class ProductListView(ListView):
    model = Product
    template_name = 'admin_pages/list_product.html'
    context_object_name = 'products'


# Класс для отображения информации о товаре
class ProductDetailView(DetailView):
    model = Product
    template_name = 'admin_pages/detail_product.html'
    context_object_name = 'product'
    slug_url_kwarg = 'slug'


class ProductsByCategoryListView(ListView):
    model = Product
    template_name = 'shop/index.html'
    context_object_name = 'products'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        categories = Category.objects.all()
        context['categories'] = categories
        return context

    def get_queryset(self):
        # если не выбрана категория товаров
        # возвращаем все товары
        if not self.kwargs.get('slug'):
            return Product.objects.all()
        # получаем название категории из URL
        # и возвращаем товары выбранной категории
        category = get_object_or_404(Category, slug=self.kwargs['slug'])
        return Product.objects.filter(category=category)


class ProductDetailClientView(DetailView):
        model = Product
        template_name = 'shop/product_detail.html'
        context_object_name = 'product'
        slug_url_kwarg = 'slug'

users/views.py
from django.shortcuts import render

# Create your views here.

shop/templates/admin_pages/add_category.html
{% extends 'admin_pages/base.html' %}

{% block content %}

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Добавить категорию</button>
</form>

{% endblock content %}

shop/templates/admin_pages/add_product.html
{% extends 'admin_pages/base.html' %}

{% block content %}

<div style="margin-top: 20px">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Добавить товар</button>
    </form>
</div>

{% endblock content %}

shop/templates/admin_pages/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta name="viewport" content="widht=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <header>
        <div class="nav-menu">
            <div class="menu-item"><a href="{% url 'staff:category_add' %}">Добавить категорию</a></div>
            <div class="menu-item"><a href="{% url 'staff:categories' %}">Посмотреть категории</a></div>
            <div class="menu-item"><a href="{% url 'staff:product_add' %}">Добавить товар</a></div>
            <div class="menu-item"><a href="{% url 'staff:products' %}">Посмотреть товары</a></div>
        </div>
    </header>

    {% block content %}
    {% endblock content %}
</body>
</html>

shop/templates/admin_pages/detail_product.html
{% extends 'admin_pages/base.html' %}

{% block content %}

<div class="product-detail">
    <div>
        ID товара - {{ product.pk }}
    </div>
    <div>
        Наименование - {{ product.name }}
    </div>
    <div>
        Категория - {{ product.category }}
    </div>
    <div>
        Описание - {{ product.description }}
    </div>
    <div>
        Стоимость - {{ product.price }}
    </div>
    {% if product.image %}
        <div>
            <img width="200" height="auto" src="{{ product.image.url }}">
        </div>
    {% else %}
        <div>Изображение отсутствует</div>
    {% endif %}
    <div>
        {% if product.available %}
            <span>Доступен к продаже</span>
        {% else %}
            <span>Не доступен к продаже</span>
        {% endif %}
    <div>
        Дата создания позиции: <span> {{ product.created_at }}</span>
    </div>

</div>

{% endblock content %}

shop/templates/admin_pages/list_category.html
{% extends 'admin_pages/base.html' %}

{% block content %}

<div>
    {% for category in categories %}
    <div>
        <b>{{ category.pk }}.{{ category.name }}</b>
        <br>
        <i>{{ category.description }}</i>
        <br>
    </div>
    {% endfor %}
</div>

{% endblock content %}

shop/templates/admin_pages/list_product.html
{% extends 'admin_pages/base.html' %}
{% load static  %}
{% block content %}

<div>
    {% for product in products %}
        <div>
            <div>
                <a href="{{ product.get_absolute_url }}">
                    <b>{{ product.pk }}. {{ product.name }}</b>
                </a>
            </div>

            <div>Категория товара: <span>{{ product.category }}</span></div>
            <div><i>{{ product.description }}</i></div>
            <div>
                {% if product.image %}
                    <img width="200" height="auto" src="{{ product.image.url }}">
                {% else %}
                    <img src="{% static 'img/no_image.png'%}" width="150px" height="auto">
                {% endif %}
            </div>
            <div>Цена: <span>{{ product.price }}</span></div>
            <div>
                {% if product.available %}
                    <span>Доступен к продаже</span>
                {% else %}
                    <span>Не доступен к продаже</span>
                {% endif %}
            </div>
            <div>Дата создания позиции: <span>{{ product.created_at }}</span></div>
        </div>
    {% endfor %}
</div>

{% endblock content %}

shop/templates/admin_pages/update_category.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

shop/templates/admin_pages/update_product.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

shop/templates/shop/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
    {% endblock title %}

    <meta name="viewport" content="widht=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <header>
        <div class="nav-menu">
            <div class="menu-item"><a href="">Главная</a></div>
            <div class="menu-item"><a href="">Корзина</a></div>
            <div class="menu-item"><a href="">Заказы</a></div>
            <div class="menu-item"><a href="">Личный кабинет</a></div>
        </div>
    </header>

    {% block content %}
    {% endblock content %}
</body>
</html>

shop/templates/shop/index.html
{% extends 'shop/base.html' %}
{% load static  %}

{% block title %}
<title>Мой магазин</title>
{% endblock title %}

{% block content %}
<div class="main">
    <div class="categories">
        <ul>
            {% for category in categories %}
            <li>
                <a href="{% url 'shop:index_category' category.slug %}">{{ category.name }}</a>
            </li>
            {% endfor %}
        </ul>
    </div>
    <div class="products">
        {% for product in products %}
        <div class="product-item">
            <div class="product-item__name">
                <a href="{% url 'shop:product_detail' slug=product.slug %}">{{ product.name }}</a>
            </div>
            <div class="product-item__price"> {{ product.price }}</div>
            <div class="product-item__image">
                {% if product.image %}
                    <img width="200" height="auto" src="{{ product.image.url }}">
                {% else %}
                    <img src="{% static 'img/no_image.png'%}" width="150px" height="auto">
                {% endif %}
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

shop/templates/shop/product_detail.html
{% extends 'shop/base.html' %}
{% load static %}
{% block content %}

<div class="product-detail">
    <div>
        ID товара - {{ product.pk }}
    </div>
    <div>
        Наименование - {{ product.name }}
    </div>
    <div>
        Категория - {{ product.category }}
    </div>
    <div>
        Описание - {{ product.description }}
    </div>
    <div>
        Стоимость - {{ product.price }}
    </div>
    {% if product.image %}
        <div>
            <img width="200" height="auto" src="{{ product.image.url }}">
        </div>
    {% else %}
        <div>Изображение отсутствует</div>
    {% endif %}
    <div>
        {% if product.available %}
            <span>Доступен к продаже</span>
        {% else %}
            <span>Не доступен к продаже</span>
        {% endif %}
    <div>
        Дата создания позиции: <span> {{ product.created_at }}</span>
    </div>

</div>

{% endblock content %}